(function(){
 'use strict';
 const C=window.AbrxsReview,D=window.AbrxsDrive,$=id=>document.getElementById(id),key='abrxs-review-project-v1';
 const fresh=()=>({format:key,name:'Proyecto nuevo',source:'',units:[],granularity:'frase',clips:[],notes:[]});
 let p=fresh(),active='',selection=[],selectionDone=false,videoSource='',videoName='',videoKind='',objectURL='',driveFile=null,endPreview=null,log=[],sourceEpoch=0,wordPage=0;
 function say(message,error=false){$('notice').textContent=message;log.push(new Date().toLocaleTimeString()+' '+message);log=log.slice(-150);$('log').textContent=log.join('\n');if(error)$('activity').hidden=false;}
 function save(){try{localStorage.setItem(key,JSON.stringify(p));$('saved').textContent='Guardado local';}catch(e){$('saved').textContent='Sin guardar';say('No se pudo guardar en el navegador. Descarga Guardar proyecto ahora.',true);}}
 function handle(fn){return async function(){try{await fn.apply(this,arguments);}catch(e){if(e.name!=='AbortError')say(e.message||String(e),true);}};}
 function download(name,data,type='application/json'){const blob=new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);say('Archivo preparado: '+name+'. Si Safari lo abre, usa Compartir → Guardar en Archivos.');}
 function exportCopy(){download('PROYECTO_ABRXS_REVIEW.json',JSON.stringify(p,null,2));}
 function button(label,fn){const b=document.createElement('button');b.textContent=label;b.onclick=handle(fn);return b;}
 let online=false,driveDuration=NaN,folderFiles=[],folderTrail=[],mediaTimer=0;
 const smallClip=f=>Number(f?.size)>0&&Number(f.size)<=32*1024*1024&&f.capabilities?.canDownload!==false;
 const mediaStatus=document.createElement('p');mediaStatus.id='media-status';mediaStatus.setAttribute('role','status');$('player-help').before(mediaStatus);
 function status(text){mediaStatus.textContent=text;}
 function cancelLoad(){clearTimeout(mediaTimer);mediaTimer=0;D.cancelMedia?.();}
 function mediaFailure(message){cancelLoad();$('player').pause();status(message+(driveFile?' Pulsa Visor de Drive o Abrir en Drive.':' Elige un archivo MP4 compatible.'));say(mediaStatus.textContent);}
 function nativeSource(url,epoch){if(epoch!==sourceEpoch)return;mode(false);$('drive-player').removeAttribute('src');endPreview=null;$('player').src=url;$('player').load();status('Cargando video…');mediaTimer=setTimeout(()=>{if(epoch===sourceEpoch)mediaFailure('No se pudo preparar el video en este navegador.');},20000);}
 async function loadNative(file,complete=false){cancelLoad();const epoch=++sourceEpoch;endPreview=null;$('player').pause();$('drive-player').removeAttribute('src');mode(false);status(complete?'Cargando clip completo en memoria…':'Preparando streaming…');try{const url=await (complete?D.blob(file):D.media(file));if(epoch!==sourceEpoch){if(complete)URL.revokeObjectURL(url);return;}if(complete){if(objectURL)URL.revokeObjectURL(objectURL);objectURL=url;}nativeSource(url,epoch);}catch(e){if(epoch===sourceEpoch&&e.name!=='AbortError')mediaFailure(e.message);}}
 function mode(useOnline){online=useOnline;$('player').pause();$('player').hidden=online;$('drive-player').hidden=!online;for(const id of ['range-play','full-play']){$(id).disabled=online;$(id).hidden=online;}$('clock').textContent=online?'Visor de Google · notas con tiempos manuales':C.stamp($('player').currentTime||0);$('drive-online').classList.toggle('active',online);$('drive-precision').classList.toggle('active',!online);$('player-help').textContent=online?'Usa únicamente los controles de Google. Para anotar, escribe los tiempos de su contador en Desde y Hasta. Si los controles del iPhone tapan el video, toca una vez fuera de ellos o abre en Drive.':'Las notas siempre usan tiempos introducidos manualmente. El contador de reproducción es solo una referencia; el streaming requiere una sesión y un formato compatible.';}
 function clearVideo(){sourceEpoch++;cancelLoad();status('');const photo=document.getElementById('review-photo');if(photo)photo.hidden=true;$('player').pause();$('player').removeAttribute('src');$('player').load();$('drive-player').removeAttribute('src');mode(false);driveDuration=NaN;if(objectURL)URL.revokeObjectURL(objectURL);objectURL='';endPreview=null;driveFile=null;videoSource='';videoName='';videoKind='';$('video-title').textContent='Tu siguiente montaje';for(const id of ['download-video','drive-online','drive-precision','open-drive'])$(id).hidden=true;$('open-drive').removeAttribute('href');}
 function selected(){if(!selection.length)throw Error('Toca el inicio y el final en la transcripción.');const[a,b]=selection;const units=p.units.slice(Math.min(a,b??a),Math.max(a,b??a)+1);return {start:units[0].start,end:units.at(-1).end,text:units.map(u=>u.text).join(' ')};}
 function play(start,end){if(online)throw Error('Referencia '+C.stamp(start)+' → '+C.stamp(end)+'. En el visor de Google busca ese intervalo manualmente, o cambia a Reproductor con tiempos.');if(!$('player').getAttribute('src'))throw Error('Selecciona primero un video reproducible.');if(!Number.isFinite($('player').duration))throw Error('Espera a que carguen los tiempos del video.');if(start<0||end<=start||end>$('player').duration+.05)throw Error('El intervalo no corresponde a la duración de este video.');endPreview=end;$('player').currentTime=start;return $('player').play();}
 function requireMaster(){if(!p.source.trim())throw Error('Indica el nombre exacto del máster.');if(videoName!==p.source)throw Error('Para previsualizar estos bloques abre el máster cuyo nombre coincide con el indicado. No se usan los tiempos del montaje como si fueran los del original.');}
 function clip(){return p.clips.find(c=>c.id===active);}
 function render(){
   $('project-name').value=p.name;$('master-name').value=p.source;
   $('clip-select').replaceChildren(...p.clips.map(c=>{const o=document.createElement('option');o.value=c.id;o.textContent=c.title;return o;}));
   if(!clip())active=p.clips[0]?.id||'';$('clip-select').value=active;$('clip-title').value=clip()?.title||'';
   renderWords();renderBlocks();renderNotes();renderMap();window.dispatchEvent(new CustomEvent('review-project'));
 }
 function renderWords(){
   const words=$('words');words.replaceChildren();const[a,b]=selection;
   wordPage=Math.min(wordPage,Math.max(0,Math.ceil(p.units.length/400)-1));
   $('words-prev').disabled=wordPage===0;$('words-next').disabled=(wordPage+1)*400>=p.units.length;$('words-page').textContent=(wordPage+1)+' / '+Math.max(1,Math.ceil(p.units.length/400));
   p.units.slice(wordPage*400,(wordPage+1)*400).forEach((u,j)=>{const i=wordPage*400+j,btt=button(u.text,()=>{if(!selection.length||selectionDone){selection=[i];selectionDone=false;}else{selection=[selection[0],i];selectionDone=true;}renderWords();});btt.className='word';btt.title=C.stamp(u.start)+' → '+C.stamp(u.end);if(selection.length&&i>=Math.min(a,b??a)&&i<=Math.max(a,b??a))btt.classList.add('selected');words.append(btt);});
   $('selection-help').textContent=p.units.length?('Selección por '+p.granularity+' · '+p.units.length+' fragmentos. Toca inicio y final.'):'Carga una transcripción con tiempos. No se inventan tiempos por palabra.';
 }
 function renderBlocks(){
   const list=$('blocks'),timeline=$('timeline');list.replaceChildren();timeline.replaceChildren();const c=clip();if(!c)return;
   c.blocks.forEach((b,i)=>{
     const card=document.createElement('div');card.className='block';const title=document.createElement('strong');title.textContent=String(i+1).padStart(2,'0')+' · '+C.stamp(b.start)+' → '+C.stamp(b.end);const text=document.createElement('p');text.textContent=b.text;
     const row=document.createElement('div');row.className='row';row.append(button('▶ Referencia',()=>{requireMaster();return play(b.start,b.end);}),button('↑',()=>{if(i>0)[c.blocks[i-1],c.blocks[i]]=[c.blocks[i],c.blocks[i-1]];save();renderBlocks();renderMap();}),button('↓',()=>{if(i<c.blocks.length-1)[c.blocks[i+1],c.blocks[i]]=[c.blocks[i],c.blocks[i+1]];save();renderBlocks();renderMap();}),button('Quitar',()=>{c.blocks.splice(i,1);save();renderBlocks();renderMap();}));
     const fields=document.createElement('div');fields.className='time-row';for(const k of ['start','end']){const label=document.createElement('label');label.textContent=k==='start'?'Inicio del máster':'Final del máster';const input=document.createElement('input');input.value=C.stamp(b[k]);input.onchange=handle(()=>{const next={...b,[k]:C.seconds(input.value)};C.unit(next);Object.assign(b,next);save();renderBlocks();renderMap();});label.append(input);fields.append(label);}const role=document.createElement('select');role.setAttribute('aria-label','Función del bloque');for(const r of ['HOOK','BODY','CTA']){const o=document.createElement('option');o.value=r;o.textContent=r;role.append(o);}role.value=b.role||'BODY';role.onchange=()=>{b.role=role.value;save();};fields.append(role);
     card.append(title,text,fields,row);list.append(card);const segment=button(String(i+1)+' · '+(b.end-b.start).toFixed(1)+' s',()=>{requireMaster();return play(b.start,b.end);});segment.className='segment';segment.style.width=Math.min(300,Math.max(80,(b.end-b.start)*5))+'px';timeline.append(segment);
   });
 }
 function renderNotes(){
   $('note-list').replaceChildren(...p.notes.map((n,i)=>{const card=document.createElement('div');card.className='note';const t=document.createElement('strong');t.textContent=n.kind+' · '+C.stamp(n.start)+' → '+C.stamp(n.end);const text=document.createElement('p');text.textContent=n.source+'\n'+n.text;const row=document.createElement('div');row.className='row';row.append(button('Ver referencia',()=>{if(videoSource!==n.sourceKey)throw Error('Abre el mismo archivo al que pertenece esta nota: '+n.source);return play(n.start,n.end>n.start?n.end:Math.min(n.start+5,$('player').duration));}),button('Eliminar',()=>{p.notes.splice(i,1);save();renderNotes();}));card.append(t,text,row);return card;}));
 }
 function renderMap(){const container=$('nodes');container.replaceChildren();const node=(title,text)=>{const el=document.createElement('div');el.className='node';const h=document.createElement('strong');h.textContent=title;const body=document.createElement('p');body.textContent=text;el.append(h,body);container.append(el);};node('MÁSTER · '+(p.source||'Sin asignar'),p.units.length+' fragmentos de transcripción');for(const c of p.clips)node(c.title,c.blocks.length+' bloques · '+c.blocks.reduce((a,b)=>a+b.end-b.start,0).toFixed(1)+' s\n'+c.blocks.map(b=>b.text).join(' / '));node('ENTREGA',p.notes.length+' correcciones · TXT / JSON / Copia del proyecto');}
 try{const raw=localStorage.getItem(key);if(raw)p=C.validateProject(JSON.parse(raw));$('client-id').value=localStorage.getItem('abrxs-review-client-id')||'';}catch(e){say('El borrador local no pudo abrirse. No se sobrescribe hasta que guardes: '+e.message,true);}
 $('project-name').onchange=()=>{p.name=$('project-name').value.trim()||'Proyecto';save();};$('master-name').onchange=()=>{if(p.clips.some(c=>c.blocks.length)&&!confirm('Cambiar el máster no cambia los tiempos. ¿Continuar?'))return render();p.source=$('master-name').value.trim();save();renderMap();};
 $('backup').onclick=handle(exportCopy);$('new-project').onclick=handle(()=>{if(!confirm('Primero se descargará una copia del proyecto actual. ¿Crear uno nuevo?'))return;exportCopy();clearVideo();p=fresh();active='';selection=[];save();render();});
 $('import-project').onchange=handle(async e=>{const f=e.target.files[0];if(!f)return;if(f.size>30*1024*1024)throw Error('Copia demasiado grande.');const next=C.validateProject(JSON.parse(await f.text()));if(!confirm('Se descargará una copia actual antes de abrir la nueva. ¿Continuar?'))return;exportCopy();clearVideo();p=next;active='';selection=[];save();render();});
 $('load-google').onclick=handle(async()=>{const id=$('client-id').value.trim();if(!/^[\w.-]+\.apps\.googleusercontent\.com$/.test(id))throw Error('Introduce tu ID OAuth web público.');localStorage.setItem('abrxs-review-client-id',id);await D.load();$('connect').disabled=false;say('Inicio de sesión listo. Pulsa Iniciar sesión en Drive.');});
 $('connect').onclick=handle(async()=>{await D.connect($('client-id').value.trim());$('disconnect').disabled=false;$('drive-settings').open=false;$('connect').textContent='Reconectar Drive';say('Drive conectado en modo lectura. Abre una carpeta.');});
 $('disconnect').onclick=handle(async()=>{listing++;clearVideo();await D.disconnect();folderFiles=[];folderTrail=[];renderBrowser();renderFiles();$('disconnect').disabled=true;$('connect').textContent='Iniciar sesión en Drive';say('Sesión cerrada. Tus fichas y notas locales se conservan.');});
 let listing=0;
 const photo=document.createElement('img');photo.id='review-photo';photo.hidden=true;photo.alt='Imagen en revisión';$('player').before(photo);
 async function selectDriveFile(f){
   clearVideo();photo.hidden=true;driveFile=f;videoName=f.name;videoSource='drive:'+f.id;videoKind=f.mimeType?.startsWith('image/')?'image':'drive';
   driveDuration=Number(f.videoMediaMetadata?.durationMillis)/1000;if(!(driveDuration>0))driveDuration=NaN;
   $('video-title').textContent=f.name;$('open-drive').hidden=false;$('open-drive').href='https://drive.google.com/file/d/'+encodeURIComponent(f.id)+'/view'+(f.resourceKey?'?resourcekey='+encodeURIComponent(f.resourceKey):'');
   if(videoKind==='image'){
     const epoch=sourceEpoch,url=await D.media(f);if(epoch!==sourceEpoch)return;photo.src=url;photo.hidden=false;$('player').hidden=true;$('drive-player').hidden=true;$('clock').textContent='Imagen · sin tiempos';$('note-start').value=$('note-end').value=C.stamp(0);for(const id of ['mark-now','range-play','full-play'])$(id).disabled=true;
   }else{
     for(const id of ['drive-online','drive-precision'])$(id).hidden=false;
     $('download-video').hidden=f.capabilities?.canDownload===false;
     showOnline();
   }
   renderFiles();window.dispatchEvent(new CustomEvent('review-file',{detail:f}));
   // Drive remains the default. Native playback is an explicit, optional action.
 }
 function notesText(notes=p.notes){return 'ABRXS REVIEW · '+p.name+'\nTIEMPOS DEL ARCHIVO REVISADO, NO DEL MÁSTER.\n\n'+notes.map(n=>`${n.source}\nID: ${n.driveId||n.sourceKey}\nArchivo: ${n.driveUrl||'Local'}\nCarpeta: ${n.folderPath||'No registrada'}\nEnlace de carpeta: ${n.folderUrl||'Local'}\n[${C.stamp(n.start)} --> ${C.stamp(n.end)}] ${n.kind}\n${n.text}`).join('\n\n');}
 window.AbrxsWeb={say,select:selectDriveFile,browse,get files(){return folderFiles;},get trail(){return folderTrail;},get project(){return p;},get current(){return driveFile;},notesText,download,save,render,loadTranscript(raw){const result=C.transcript(raw);p.units=result.units;p.granularity=result.granularity;save();render();}};
 function renderFiles(){const q=$('file-search').value.trim().toLocaleLowerCase(),files=folderFiles.filter(f=>f.name.toLocaleLowerCase().includes(q));$('file-count').textContent=files.filter(f=>f.mimeType!=='application/vnd.google-apps.folder').length+' videos · '+files.filter(f=>f.mimeType==='application/vnd.google-apps.folder').length+' carpetas';$('files').replaceChildren(...files.map(f=>{const isFolder=f.mimeType==='application/vnd.google-apps.folder';const b=button(f.name,async()=>{if(isFolder)return browse(f.id,f.name,true);return selectDriveFile({...f,parentFolder:folderTrail.at(-1),folderPath:folderTrail.map(x=>x.name).join(' / ')});});b.className='file-card '+(isFolder?'folder-card':'video-card');b.classList.toggle('selected',videoSource==='drive:'+f.id);const s=document.createElement('small');s.textContent=isFolder?'Abrir carpeta →':(f.size?(Number(f.size)/1048576).toFixed(1)+' MB':'Video')+(Number(f.videoMediaMetadata?.durationMillis)>0?' · '+C.stamp(Number(f.videoMediaMetadata.durationMillis)/1000):'');b.append(s);return b;}));if(!files.length){const p=document.createElement('p');p.textContent=q?'Sin resultados en esta carpeta.':'Esta carpeta no contiene videos ni subcarpetas.';$('files').append(p);}}
 async function browse(folder,name='Carpeta de Drive',nested=false){const epoch=++listing;say('Leyendo carpeta de Drive…');const files=await D.list(folder);if(epoch!==listing)return;folderFiles=files;const item={id:folder,name:folder?name:'Mi Drive'};folderTrail=nested?[...folderTrail,item]:[item];$('folder').value=folder;$('file-search').value='';renderBrowser();renderFiles();say(files.length+' archivos en la carpeta.');window.dispatchEvent(new CustomEvent('review-folder'));}
 function renderBrowser(){$('folder-back').disabled=folderTrail.length<2;$('breadcrumbs').replaceChildren(...folderTrail.map((f,i)=>button(f.name,async()=>{const path=folderTrail.slice(0,i+1);await browse(f.id,f.name);folderTrail=path;renderBrowser();})));}
 function showOnline(){if(!driveFile)return;++sourceEpoch;cancelLoad();endPreview=null;$('player').pause();$('player').removeAttribute('src');$('player').load();mode(true);$('drive-player').src='https://drive.google.com/file/d/'+encodeURIComponent(driveFile.id)+'/preview'+(driveFile.resourceKey?'?resourcekey='+encodeURIComponent(driveFile.resourceKey):'');status('Visor externo de Google. Si no carga o los controles tapan el video, abre el archivo directamente en Drive.');}
 $('drive-online').onclick=handle(showOnline);
 $('drive-precision').onclick=handle(async()=>{if(!driveFile)throw Error('Selecciona un video de Drive.');if(driveFile.capabilities?.canDownload===false)throw Error('El propietario permite ver pero no descargar: usa el visor online.');return loadNative(driveFile,smallClip(driveFile));});
 $('folder-back').onclick=handle(async()=>{if(folderTrail.length<2)return;const path=folderTrail.slice(0,-1),last=path.at(-1);await browse(last.id,last.name);folderTrail=path;renderBrowser();});
 $('folder-refresh').onclick=handle(async()=>{const path=folderTrail.slice();await browse(path.at(-1)?.id||$('folder').value,path.at(-1)?.name||'Carpeta de Drive');if(path.length){folderTrail=path;renderBrowser();}});
 $('file-search').oninput=renderFiles;
 $('browse').onclick=handle(()=>browse($('folder').value));$('root').onclick=handle(()=>{ $('folder').value='';return browse('');});
 $('download-video').onclick=handle(async()=>{if(!driveFile)throw Error('Selecciona un video.');if(!confirm('Se descargará el clip completo a memoria (máximo 150 MB). ¿Continuar?'))return;return loadNative(driveFile,true);});
 $('local-video').onchange=handle(e=>{const f=e.target.files[0];if(!f)return;clearVideo();objectURL=URL.createObjectURL(f);videoName=f.name;videoSource='local:'+f.name+':'+f.size+':'+f.lastModified;videoKind='local';nativeSource(objectURL,sourceEpoch);$('video-title').textContent=f.name;say('Video local abierto. No se sube a internet.');});
 $('player').ontimeupdate=()=>{if(online)return;$('clock').textContent=C.stamp($('player').currentTime);if(endPreview!==null&&$('player').currentTime>=endPreview){$('player').pause();endPreview=null;}};
 $('player').addEventListener('loadedmetadata',()=>{if(online||!$('player').getAttribute('src'))return;try{$('player').currentTime=0;}catch{}$('clock').textContent=C.stamp(0);});
 $('player').addEventListener('canplay',()=>{if(online||!$('player').getAttribute('src'))return;clearTimeout(mediaTimer);status('Listo para reproducir. Usa los controles del video; las notas siguen siendo manuales.');});
 $('player').onerror=()=>{if(!online&&$('player').getAttribute('src'))mediaFailure('No se pudo reproducir el archivo (error '+($('player').error?.code||'desconocido')+'). Puede ser un formato incompatible, una sesión caducada o un fallo de lectura.');};
 $('full-play').onclick=handle(()=>{endPreview=null;return $('player').play();});$('range-play').onclick=handle(()=>play(C.seconds($('note-start').value),C.seconds($('note-end').value)));
 $('mark-now').textContent='Editar tiempos manuales';$('mark-now').onclick=()=>{$('note-start').focus();};
 $('add-note').onclick=handle(()=>{if(!videoSource)throw Error('Selecciona el archivo que vas a revisar.');const start=C.seconds($('note-start').value),end=C.seconds($('note-end').value),text=$('note-text').value.trim(),duration=online?driveDuration:$('player').duration;if(end<start||(videoKind!=='image'&&Number.isFinite(duration)&&(end>duration+.05||start>duration)))throw Error('Tiempos fuera del video.');if(!text)throw Error('Escribe la corrección.');p.notes.push({start,end,text,kind:$('note-kind').value,source:videoName,sourceKey:videoSource,timebase:'reviewed-file-seconds',sourceKind:videoKind,timeEntry:'manual',driveId:driveFile?.id,driveUrl:driveFile?'https://drive.google.com/file/d/'+driveFile.id+'/view':null,folderId:driveFile?.parentFolder?.id||driveFile?.parents?.[0],folderPath:driveFile?.folderPath||folderTrail.map(f=>f.name).join(' / '),folderUrl:(driveFile?.parentFolder?.id||driveFile?.parents?.[0])?'https://drive.google.com/drive/folders/'+(driveFile?.parentFolder?.id||driveFile?.parents?.[0]):null});save();renderNotes();renderMap();$('note-text').value='';say('Nota guardada con referencia al archivo y tiempos manuales.');});
 $('notes-json').onclick=handle(()=>download('REVISION_ABRXS.json',JSON.stringify({format:'abrxs-review-notes-v1',project:p.name,notes:p.notes},null,2)));
 $('notes-txt').onclick=handle(()=>download('REVISION_ABRXS.txt',notesText(),'text/plain;charset=utf-8'));
 $('transcript').onchange=handle(async e=>{const f=e.target.files[0];if(!f)return;if(f.size>20*1024*1024)throw Error('Transcripción demasiado grande.');const result=C.transcript(await f.text());p.units=result.units;p.granularity=result.granularity;selection=[];save();renderWords();renderMap();say('Transcripción cargada por '+result.granularity+'. Comprueba que corresponde al máster indicado.');});
 $('words-prev').onclick=()=>{wordPage=Math.max(0,wordPage-1);renderWords();};$('words-next').onclick=()=>{wordPage++;renderWords();};
 $('clear-selection').onclick=()=>{selection=[];selectionDone=false;renderWords();};$('preview-text').onclick=handle(()=>{requireMaster();const b=selected();return play(b.start,b.end);});
 function createClip(){const c={id:crypto.randomUUID(),title:'Clip '+(p.clips.length+1),blocks:[]};p.clips.push(c);active=c.id;save();render();}
 $('new-clip').onclick=handle(createClip);$('add-block').onclick=handle(()=>{if(!p.source)throw Error('Indica el nombre del máster de la transcripción.');const block=selected();if(!clip())createClip();clip().blocks.push({...block,role:clip().blocks.length?'BODY':'HOOK'});save();renderBlocks();renderMap();say('Bloque añadido. Usa ↑ ↓ para ordenar el montaje.');});
 $('clip-select').onchange=()=>{active=$('clip-select').value;render();};$('clip-title').onchange=()=>{if(clip()){clip().title=$('clip-title').value.trim()||'Clip';save();render();}};$('delete-clip').onclick=()=>{if(clip()&&confirm('¿Eliminar esta ficha y sus bloques?')){p.clips=p.clips.filter(c=>c.id!==active);save();render();}};
 function exportEditorial(ext){if(!p.source)throw Error('Indica el nombre exacto del máster.');download('DECISIONES_ABRXS.'+ext,JSON.stringify(C.editorial(p),null,2),ext==='txt'?'text/plain;charset=utf-8':'application/json');}
 $('editorial-json').onclick=handle(()=>exportEditorial('json'));$('editorial-txt').onclick=handle(()=>exportEditorial('txt'));
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(t=>t.hidden=t.id!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(t=>t.classList.toggle('active',t===b));});
 function toggleLog(show){$('activity').hidden=!show;$('log-toggle').setAttribute('aria-expanded',String(show));}$('log-toggle').onclick=()=>toggleLog($('activity').hidden);$('close-log').onclick=()=>toggleLog(false);$('copy-log').onclick=handle(async()=>{await navigator.clipboard.writeText(log.join('\n'));say('Diagnóstico copiado. Revisa nombres y notas antes de compartir.');});
 window.addEventListener('drive-status',e=>say(e.detail,true));window.addEventListener('error',e=>say('Error: '+e.message,true));window.addEventListener('unhandledrejection',e=>say('Error: '+(e.reason?.message||'Operación fallida'),true));
 if('serviceWorker' in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(e=>say('Modo offline no disponible: '+e.message));render();
})();
